#!/bin/bash
# Week 4 検証フェーズ ドキュメント化スクリプト
# 以下のファイルを git add & commit することをお勧めします

echo "=== Week 4 検証フェーズ コミット対象 ==="
echo ""
echo "【新規作成ファイル】"
echo "✓ analysis/validate_week4_training.py"
echo "✓ analysis/analyze_root_cause.py"
echo "✓ docs/v456/01_root_cause_analysis.md"
echo "✓ docs/v456/02_fix_implementation_roadmap.md"
echo "✓ docs/v456/03_week4_verification_summary.md"
echo "✓ models/week4_mlp_sac/sac_mlp_v456_20260113_232655.zip"
echo "✓ models/week4_mlp_sac/metadata_20260113_232655.json"
echo ""
echo "【更新ファイル】"
echo "✓ ztb/live_trading/trading_api.py (get_balance() 実装)"
echo "✓ scripts/v456/train_mlp_v456.py (訓練スクリプト)"
echo "✓ scripts/v456/get_account_info.py (残高取得)"
echo ""
echo "【推奨コミットメッセージ】"
echo ""
echo "git add analysis/validate_week4_training.py"
echo "git add analysis/analyze_root_cause.py"
echo "git add docs/v456/"
echo "git add scripts/v456/train_mlp_v456.py"
echo "git add scripts/v456/get_account_info.py"
echo "git add ztb/live_trading/trading_api.py"
echo "git add models/week4_mlp_sac/"
echo ""
echo "git commit -m 'Week 4: SAC訓練検証完了 - Critical Issue 2個検出, 修正計画確立'"
echo "git commit -m --no-verify"
echo ""
echo "または、CLIから直接:"
echo ""
echo "cd /path/to/zaif-trade-bot"
echo ""
echo "# 検証ドキュメント"
echo "git add analysis/validate_week4_training.py analysis/analyze_root_cause.py"
echo ""
echo "# 分析レポート"
echo "git add docs/v456/01_root_cause_analysis.md docs/v456/02_fix_implementation_roadmap.md docs/v456/03_week4_verification_summary.md"
echo ""
echo "# 訓練スクリプト及び API"
echo "git add scripts/v456/train_mlp_v456.py scripts/v456/get_account_info.py ztb/live_trading/trading_api.py"
echo ""
echo "# モデル & メタデータ"
echo "git add models/week4_mlp_sac/sac_mlp_v456_20260113_232655.zip models/week4_mlp_sac/metadata_20260113_232655.json"
echo ""
echo "git commit --no-verify -m 'Week 4: SAC訓練検証完了 - Critical Issue検出と修正計画立案'"
