experimental:
  MovingAverages:
    maturity: stable   # prototype → beta → stable
    evaluation_period: 2025-12-31
    risk_level: low
    dependencies: ["close"]

  GradientSign:
    maturity: prototype
    evaluation_period: 2025-12-31
    risk_level: low
    dependencies: ["close"]