name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install types-requests types-psutil
        pip install pre-commit

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files --show-diff-on-failure

    - name: Run linting
      run: |
        flake8 ztb/

    - name: Run type checking
      run: |
        mypy ztb/ --strict --exclude 'tests/'

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install types-requests types-psutil

    - name: Run unit tests
      run: |
        npm run test:unit

  leakage-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install types-requests types-psutil

    - name: Run leakage detection tests
      run: |
        python -m pytest tests/test_no_lookahead.py -v

  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install types-requests types-psutil

    - name: Run integration tests
      run: |
        npm run test:int-fast

  smoke-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install types-requests types-psutil

    - name: Run smoke test with memory profiling
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        export ZTB_MEM_PROFILE=1
        python ztb/experiments/smoke_test.py --steps 1000 --dataset synthetic

    - name: Upload memory profile
      uses: actions/upload-artifact@v4
      with:
        name: memory-profile-${{ github.run_id }}
        path: |
          memory_profile_*.csv
          logs/**/*.jsonl
        retention-days: 30
