name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install types-requests types-psutil
        pip install pre-commit

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files --show-diff-on-failure

    - name: Run tests
      run: |
        pytest -q

    - name: Run linting
      run: |
        flake8 ztb/

    - name: Run type checking
      run: |
        mypy ztb/ --strict --exclude 'tests/'

    - name: Test verified features
      run: |
        pytest -q scripts/test_verified_features.py

    - name: Test simple features
      run: |
        pytest -q scripts/test_simple_features.py

    - name: Check for secrets in code
      run: |
        # Check for hardcoded secrets/API keys in ztb/ directory
        SECRET_COUNT=$(git grep -n "\(SECRET\|API_KEY\|WEBHOOK\)" -- ztb | wc -l)
        if [ "$SECRET_COUNT" -gt 0 ]; then
          echo "Found $SECRET_COUNT potential secrets in code:"
          git grep -n "\(SECRET\|API_KEY\|WEBHOOK\)" -- ztb
          exit 1
        fi

    - name: Test all features with coingecko data
      run: |
        python scripts/test_all_features.py --dataset coingecko --bootstrap --save-debug

    - name: Archive coverage data
      run: |
        python scripts/archive_coverage.py
