name: Test Live Minimal

on:
  workflow_dispatch:
    inputs:
      exchange:
        description: "Exchange (zaif|coincheck)"
        required: true
        default: "coincheck"
      flow:
        description: "TRADE_FLOW (BUY_ONLY|SELL_ONLY|BUY_SELL|SELL_BUY)"
        required: true
        default: "BUY_ONLY"
      qty:
        description: "TEST_FLOW_QTY"
        required: true
        default: "0.001"
      rate:
        description: "TEST_FLOW_RATE (optional)"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Run minimal live test (cancel immediately)
        env:
          EXCHANGE: ${{ github.event.inputs.exchange }}
          TRADE_FLOW: ${{ github.event.inputs.flow }}
          TEST_FLOW_QTY: ${{ github.event.inputs.qty }}
          TEST_FLOW_RATE: ${{ github.event.inputs.rate }}
          DRY_RUN: '0'
          SAFETY_MODE: '1'
        run: npm run test:min-live
      - name: Upload live stats
        uses: actions/upload-artifact@v4
        with:
          name: live-stats
          path: logs/live/stats-diff-live.json
      - name: Upload live features
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: live-features
          path: |
            logs/features/**/features-*.csv
            logs/features/latest-*.json
